import { expect, test } from '@playwright/test'
import { apiBaseUrl, apiData, authHeaders, login, signInPage } from './helpers'

const createPost = async (request: Parameters<typeof login>[0], title: string) => {
  const author = await login(request, 'promptlin')
  const post = await apiData<{ id: string; title: string; version: number }>(request.post(`${apiBaseUrl}/api/posts`, { headers: authHeaders(author.accessToken), data: { title, body: 'Community Admin browser regression fixture.', category: 'Questions', tag: 'Admin', excerpt: 'Fixture' } }))
  const commenter = await login(request, 'taskops')
  const comment = await apiData<{ id: string; version: number }>(request.post(`${apiBaseUrl}/api/posts/${post.id}/comments`, { headers: authHeaders(commenter.accessToken), data: { body: 'Community Admin browser comment fixture.' } }))
  return { post, comment }
}

test('Community Admin edits, deletes, restores, and bulk disposes content', async ({ page, request }) => {
  const fixture = await createPost(request, `Community Admin E2E ${Date.now()}`)
  await signInPage(page, request, 'opsplus')
  await page.goto('/')
  await page.getByTestId('nav-admin').click()
  await page.getByRole('main').getByRole('button', { name: 'Community', exact: true }).click()
  const panel = page.getByTestId('community-admin-panel')
  await expect(panel).toBeVisible()
  await panel.getByLabel('Search').fill(fixture.post.id)
  const row = panel.locator('.task-admin-row').filter({ hasText: fixture.post.id })
  await expect(row).toBeVisible()
  await row.locator('button').click()
  await expect(panel.getByLabel('Title')).toHaveValue(fixture.post.title)
  await panel.getByLabel('Title').fill(`${fixture.post.title} edited`)
  await panel.getByLabel('Reason code').fill('e2e_community_edit')
  const update = page.waitForResponse((response) => response.url().endsWith(`/api/admin/community/posts/${fixture.post.id}`) && response.request().method() === 'PATCH')
  await panel.getByRole('button', { name: 'Save', exact: true }).click()
  expect((await update).ok()).toBeTruthy()

  await panel.getByLabel('Search').fill(fixture.post.id)
  await expect(row).toBeVisible()
  await row.locator('button').click()
  const removed = page.waitForResponse((response) => response.url().endsWith(`/api/admin/community/posts/${fixture.post.id}/delete`))
  await panel.getByRole('button', { name: 'Delete', exact: true }).click()
  expect((await removed).ok()).toBeTruthy()
  await panel.getByLabel('Deletion').selectOption('deleted')
  await panel.getByLabel('Search').fill(fixture.post.id)
  await expect(row).toBeVisible()
  await row.locator('button').click()
  const restored = page.waitForResponse((response) => response.url().endsWith(`/api/admin/community/posts/${fixture.post.id}/restore`))
  await panel.getByRole('button', { name: 'Restore', exact: true }).click()
  expect((await restored).ok()).toBeTruthy()

  await panel.getByRole('button', { name: 'Comments', exact: true }).click()
  await panel.getByLabel('Search').fill(fixture.comment.id)
  const commentRow = panel.locator('.task-admin-row').filter({ hasText: fixture.comment.id })
  await expect(commentRow).toBeVisible()
  await commentRow.getByRole('checkbox').check()
  await panel.getByLabel('Bulk action').selectOption('delete')
  await panel.getByRole('button', { name: 'Preview', exact: true }).click()
  const confirmation = panel.getByPlaceholder('DELETE COMMENTS')
  await confirmation.fill('DELETE COMMENTS')
  const bulk = page.waitForResponse((response) => response.url().endsWith('/api/admin/community/bulk') && response.request().method() === 'POST')
  await panel.getByRole('button', { name: 'Execute', exact: true }).click()
  expect((await bulk).ok()).toBeTruthy()
})

test('Community Admin remains bounded on a mobile viewport', async ({ page, request }) => {
  await createPost(request, `Community Admin mobile ${Date.now()}`)
  await page.setViewportSize({ width: 390, height: 844 })
  await signInPage(page, request, 'opsplus')
  await page.goto('/')
  await page.getByRole('button', { name: 'Toggle navigation' }).click()
  await page.getByTestId('nav-admin').click()
  await page.getByRole('main').getByRole('button', { name: 'Community', exact: true }).click()
  const panel = page.getByTestId('community-admin-panel')
  await expect(panel).toBeVisible()
  await panel.scrollIntoViewIfNeeded()
  const layout = await panel.evaluate((element) => ({ panelWidth: element.getBoundingClientRect().width, viewportWidth: window.innerWidth, overflow: [...element.querySelectorAll<HTMLElement>('*')].filter((node) => getComputedStyle(node).overflowX !== 'auto' && node.scrollWidth > node.clientWidth + 2).map((node) => node.className).filter(Boolean).slice(0, 10) }))
  expect(layout.panelWidth).toBeLessThanOrEqual(layout.viewportWidth)
  expect(layout.overflow).toEqual([])
  await page.screenshot({ path: 'test-results/community-admin-mobile.png', fullPage: true })
})
