import { expect, test } from '@playwright/test'

import { signInPage } from './helpers'

test('admin builds a promotion-gated model registry with durable route and SecretRef evidence', async ({ page, request }) => {
  await signInPage(page, request, 'opsplus')
  await page.goto('/')
  await page.getByTestId('nav-admin').click()
  await page.getByRole('button', { name: 'AI config', exact: true }).click()

  const panel = page.getByTestId('model-control-panel')
  await expect(panel).toBeVisible()
  await expect(panel).toContainText('Provider traffic is promotion-gated')

  const suffix = Date.now().toString(36)
  await panel.getByLabel('Provider key').fill(`e2e-provider-${suffix}`)
  await panel.getByLabel('Provider name').fill(`E2E Provider ${suffix}`)
  await panel.getByLabel('Provider website').fill('https://provider.example.com')
  await panel.getByRole('button', { name: 'New draft' }).click()
  await expect(panel.locator('.model-control-row').filter({ hasText: `E2E Provider ${suffix}` })).toBeVisible()

  await panel.getByRole('button', { name: 'Models', exact: true }).click()
  await panel.getByLabel('Provider').selectOption({ label: `E2E Provider ${suffix}` })
  await panel.getByLabel('Model key').fill(`e2e-model-${suffix}`)
  await panel.getByLabel('Model name').fill(`E2E Model ${suffix}`)
  await panel.getByRole('button', { name: 'New draft' }).click()
  await expect(panel.locator('.model-control-row').filter({ hasText: `E2E Model ${suffix}` })).toBeVisible()

  await panel.getByRole('button', { name: 'Versions', exact: true }).click()
  await panel.getByLabel('Model').selectOption({ label: `E2E Model ${suffix}` })
  await panel.getByLabel('Version key').fill(`v-${suffix}`)
  await panel.getByLabel('Context window').fill('8192')
  await panel.getByRole('button', { name: 'New draft' }).click()
  await expect(panel.locator('.model-control-row').filter({ hasText: `v-${suffix}` })).toBeVisible()
  await expect(panel.locator('.model-version-counts')).toContainText('0 deployments')
  await panel.getByTitle('Save capability').click()
  await panel.getByLabel('Deployment environment').selectOption('production')
  await panel.getByPlaceholder('deployment-key').fill(`route-deployment-${suffix}`)
  await panel.getByPlaceholder('region').fill('us')
  await panel.getByPlaceholder('deployment-ref').fill(`offline-ref-${suffix}`)
  await panel.getByTitle('Create deployment').click()
  await expect(panel.locator('.model-version-counts')).toContainText('1 deployments')

  await panel.getByRole('button', { name: 'Routing', exact: true }).click()
  await panel.getByLabel('Route key').fill(`route-${suffix}`)
  await panel.getByLabel('Route name').fill(`E2E Route ${suffix}`)
  await panel.getByLabel('Route environment').selectOption('production')
  await panel.getByRole('button', { name: 'New draft' }).click()
  await expect(panel.locator('.model-control-row').filter({ hasText: `E2E Route ${suffix}` })).toBeVisible()
  await panel.getByLabel('Primary deployment').selectOption({ label: `route-deployment-${suffix}` })
  await panel.getByTitle('Save route targets').click()
  await panel.getByRole('button', { name: 'active', exact: true }).click()
  await expect(panel.locator('.model-control-row').filter({ hasText: `E2E Route ${suffix}` }).locator('em')).toHaveText('active')
  await panel.getByTitle('Run route preview').click()
  await expect(panel.getByTestId('model-route-preview')).toContainText('unavailable')
  await expect(panel.getByTestId('model-route-preview')).toContainText('all_candidates_blocked')
  const governance = panel.getByTestId('model-governance-workbench')
  await expect(governance).toContainText('all_candidates_blocked')
  await expect(governance.locator('code').first()).toHaveText(/^[a-f0-9]{12}$/)

  await governance.getByRole('button', { name: 'SecretRef', exact: true }).click()
  await governance.getByLabel('SecretRef Provider').selectOption({ label: `E2E Provider ${suffix}` })
  await governance.getByLabel('SecretRef environment').selectOption('production')
  await governance.getByLabel('SecretRef purpose').fill('inference')
  await governance.getByLabel('SecretRef reference').fill(`secret://e2e/${suffix}`)
  await governance.getByLabel('SecretRef external version').fill('v1')
  await governance.getByLabel('SecretRef owner').fill('opsplus')
  await governance.getByLabel('SecretRef checksum').fill('a'.repeat(64))
  await governance.getByRole('button', { name: 'Append reference' }).click()
  await expect(governance).toContainText(`secret://e2e/${suffix}`)

  await governance.getByRole('button', { name: 'Operations', exact: true }).click()
  await governance.getByLabel('Operations Provider').selectOption({ label: `E2E Provider ${suffix}` })
  await governance.getByLabel('Operations environment').selectOption('staging')
  await governance.getByLabel('Operations workspace').selectOption('image')
  await governance.getByLabel('Operations model family').fill(`e2e-model-${suffix}`)
  await governance.getByRole('button', { name: 'Create policy' }).click()
  await expect(governance).toContainText('provider_policy_draft')
  await governance.getByLabel('Health policy').selectOption({ label: `E2E Provider ${suffix} · staging · image` })
  await governance.getByLabel('Health source type').selectOption('fixture_probe')
  await governance.getByLabel('Health source reference').fill(`fixture:health:${suffix}`)
  await governance.getByLabel('Health latency').fill('120')
  await governance.getByLabel('Health success rate').fill('9990')
  await governance.getByRole('button', { name: 'Append health' }).click()
  await expect(governance).toContainText('healthy')

  await governance.getByRole('button', { name: 'Evaluations', exact: true }).click()
  await expect(governance.getByTestId('model-evaluation-gate')).toBeVisible()
  await governance.getByLabel('Evaluation suite key').fill(`e2e-evaluation-${suffix}`)
  await governance.getByLabel('Evaluation suite name').fill(`E2E Evaluation ${suffix}`)
  await governance.getByLabel('Evaluation modality').selectOption('image')
  await governance.getByLabel('Quality input hash').fill('1'.repeat(64))
  await governance.getByLabel('Quality expected hash').fill('2'.repeat(64))
  await governance.getByLabel('Safety input hash').fill('3'.repeat(64))
  await governance.getByLabel('Safety expected hash').fill('4'.repeat(64))
  await governance.getByRole('button', { name: 'Append suite' }).click()
  await governance.getByLabel('Evaluation policy suite').selectOption({ label: `e2e-evaluation-${suffix} v1` })
  await governance.getByLabel('Evaluation policy key').fill(`e2e-policy-${suffix}`)
  await governance.getByLabel('Evaluation policy environment').selectOption('production')
  await governance.getByRole('button', { name: 'Append policy' }).click()
  await governance.getByLabel('Evaluation run suite').selectOption({ label: `e2e-evaluation-${suffix} v1` })
  await governance.getByLabel('Evaluation run policy').selectOption({ label: `e2e-policy-${suffix} v1` })
  await governance.getByLabel('Evaluation model version').selectOption({ label: `v-${suffix}` })
  await governance.getByLabel('Evaluation deployment').selectOption({ label: `route-deployment-${suffix}` })
  await governance.getByLabel('Evaluation output hash').fill('5'.repeat(64))
  await governance.getByRole('button', { name: 'Record run' }).click()
  await expect(governance).toContainText('passed · 10000/10000')
  await governance.getByLabel('Evaluation baseline').selectOption({ label: 'passed · 10000' })
  await governance.getByRole('button', { name: 'Record run' }).click()
  await expect(governance).toContainText('delta 0')

  await governance.getByRole('button', { name: 'Legal review', exact: true }).click()
  await expect(governance.getByTestId('provider-legal-gate')).toBeVisible()
  await governance.getByLabel('Legal Provider').selectOption({ label: `E2E Provider ${suffix}` })
  await governance.getByLabel('Legal model version').selectOption({ label: `v-${suffix}` })
  await governance.getByLabel('Legal environment').selectOption('production')
  await governance.getByLabel('Legal allowed regions').fill('us')
  await governance.getByLabel('Legal geography status').selectOption('approved')
  await governance.getByLabel('Legal DPA status').selectOption('executed')
  await governance.getByLabel('Legal retention status').selectOption('approved')
  await governance.getByLabel('Legal training status').selectOption('contractual_no_training')
  await governance.getByLabel('Legal copyright status').selectOption('approved')
  await governance.getByLabel('Legal SLA status').selectOption('approved')
  await governance.getByLabel('Legal evidence hash').fill('6'.repeat(64))
  await governance.getByLabel('Legal counsel reference').fill(`e2e-counsel-${suffix}`)
  await governance.getByLabel('Legal product owner reference').fill(`e2e-product-owner-${suffix}`)
  await governance.getByRole('button', { name: 'Append review' }).click()
  await expect(governance).toContainText(`E2E Provider ${suffix}`)
  await expect(governance.getByTestId('provider-legal-gate')).toContainText('1 / 1 current scopes approved')

  await governance.getByRole('button', { name: 'Promotions', exact: true }).click()
  const requestApproval = governance.getByRole('button', { name: 'Request approval' })
  await expect(requestApproval).toBeDisabled()
  await governance.getByLabel('Promotion deployment').selectOption({ label: `route-deployment-${suffix}` })
  await governance.getByLabel('Promotion route policy').selectOption({ label: `E2E Route ${suffix}` })
  await expect(governance.getByLabel('Promotion route revision')).not.toHaveValue('')
  await governance.getByLabel('Promotion SecretRef').selectOption({ label: 'inference · v1' })
  await governance.getByLabel('Promotion evaluation run').selectOption({ index: 1 })
  await governance.getByLabel('Promotion legal review').selectOption({ index: 1 })
  await governance.getByLabel('Promotion artifact version').fill(`v-${suffix}`)
  await governance.getByLabel('Promotion rollback version').fill(`v-${suffix}-rollback`)
  await governance.getByLabel('Promotion summary').fill(`E2E promotion ${suffix}`)
  await expect(requestApproval).toBeEnabled()
  await requestApproval.click()
  await expect(governance).toContainText(`v-${suffix}`)

  await page.setViewportSize({ width: 390, height: 844 })
  const layout = await panel.evaluate((element) => {
    const width = document.documentElement.clientWidth
    const panelRect = element.getBoundingClientRect()
    const overflow = [...element.querySelectorAll('*')].map((child) => {
      const rect = child.getBoundingClientRect()
      return { tag: child.tagName, className: child.className, left: Math.round(rect.left), right: Math.round(rect.right), width: Math.round(rect.width) }
    }).filter((item) => item.right > width + 1).slice(0, 8)
    return { width, panel: { left: Math.round(panelRect.left), right: Math.round(panelRect.right), width: Math.round(panelRect.width), grid: getComputedStyle(element).gridTemplateColumns }, overflow }
  })
  expect(layout.overflow, JSON.stringify(layout)).toEqual([])
})

test('moderator can inspect the model registry but cannot mutate it', async ({ page, request }) => {
  await signInPage(page, request, 'legalpixel')
  await page.goto('/')
  await page.getByTestId('nav-admin').click()
  await page.getByRole('button', { name: 'AI config', exact: true }).click()

  const panel = page.getByTestId('model-control-panel')
  await expect(panel).toBeVisible()
  await expect(panel.getByRole('button', { name: 'New draft' })).toHaveCount(0)
  await expect(panel.getByTitle('Export configuration')).toBeVisible()
  await panel.getByRole('button', { name: 'Routing', exact: true }).click()
  await expect(panel.getByRole('button', { name: 'New draft' })).toHaveCount(0)
  const governance = panel.getByTestId('model-governance-workbench')
  await governance.getByRole('button', { name: 'Evaluations', exact: true }).click()
  await expect(governance.getByTestId('model-evaluation-gate')).toBeVisible()
  await expect(governance.getByTestId('evaluation-suite-form')).toHaveCount(0)
  await expect(governance.getByTestId('evaluation-run-form')).toHaveCount(0)
  await governance.getByRole('button', { name: 'Legal review', exact: true }).click()
  await expect(governance.getByTestId('provider-legal-gate')).toBeVisible()
  await expect(governance.getByTestId('provider-legal-form')).toHaveCount(0)
})
